theme: jekyll-theme-hacker
title: www.ScottMacri.com
name: www.ScottMacri.com
description: Bits-N-Bytes | Learn to code like a pro!

github:
  repository_url: http://www.ScottMacri.com
  
social-network-links:
  linkedin: scottmacri
  
share-links-active:
  twitter: true
  facebook: true
  email: true
  github: true
  linkedin: true
